
--Q1 What is the total revenue generated by male vs female customers?

SELECT gender,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender

--Q2 which customer used a discount but still spend more than the average purchase amount?

SELECT 
	customer_id,
	purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount)FROM customer)

--Q3 Wich are the top 5 products with higest average review rating

SELECT 
	TOP 5 item_purchased,
	ROUND(AVG(review_rating),2) avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_product_rating DESC

--Q4 Compare the avarage purchase amounts between Standard and Express Shipping.

SELECT
	shipping_type,
	ROUND(AVG(purchase_amount), 2) avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type

--Q5 Do subscribe customer spend more ? Compare average spend and total revenue between subscribe and non-subscribe

SELECT
	subscription_status,
	COUNT(customer_id) total_customers,
	ROUND(AVG(purchase_amount),2) avg_spend,
	ROUND(SUM(purchase_amount), 2) total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC

--Q6 Which 5 products have the higest percentage of purchase with discount applied

SELECT
	TOP 5 item_purchased,
	ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100 / COUNT(purchase_amount),2) discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--Q7 Segment customers into New, Returing, and Loyal based on their total number of previous purchased and show the count of each segment

WITH customer_type AS (
	SELECT 
		CASE
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returing'
		ELSE 'Loyal'
	END AS customer_segment
	FROM customer
)
SELECT 
	customer_segment,
	COUNT(*) AS customer_count
FROM customer_type
GROUP BY customer_segment;

--Q8 What are the top 3 most purchased products within each category

WITH product_sales AS (
	SELECT
		category,
		item_purchased,
		COUNT(*) AS total_orders
	FROM customer
	GROUP BY category,item_purchased
),
ranked_product AS(
	SELECT
		category,
		item_purchased,
		total_orders,
		ROW_NUMBER() OVER (PARTITION BY category ORDER BY total_orders DESC) AS rank_in_categories
	FROM product_sales
)

SELECT 
	rank_in_categories,
	category,
	item_purchased,
	total_orders
FROM ranked_product
WHERE rank_in_categories <= 3

--Q9 Are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe?
SELECT 
	subscription_status,
	COUNT(*) repeated_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10 What is the revenue contribution of each age group?

SELECT
	age_group,
	COUNT(*) total_customers,
	SUM(purchase_amount) total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC